apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps-homelab
  namespace: flux-system
spec:
  dependsOn:
    - name: infrastructure-sources
    - name: infrastructure-controllers
    - name: infrastructure-configs
    - name: infrastructure-secrets
  interval: 1h
  retryInterval: 1m
  timeout: 10m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./k8s/apps/dev/homelab
  prune: true
  wait: true
