apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: project-apps
  namespace: argocd
spec:
  goTemplate: true
  generators:
    - git:
        repoURL: https://github.com/Axot017/homelab.git
        revision: main
        directories:
          - path: kubernetes/apps/*
          - path: kubernetes/apps/argocd
            exclude: true
  template:
    metadata:
      name: '{{ .path.basename }}-apps'
      namespace: argocd
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: '{{ .path.basename }}'
      source:
        repoURL: https://github.com/Axot017/homelab.git
        targetRevision: main
        path: '{{ .path.path }}'
      destination:
        server: https://kubernetes.default.svc
        namespace: argocd
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
