---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-tunnel-token
  namespace: cloudflare
spec:
  encryptedData:
    token: AgBKVlKG5Q2qEe0RqXFF9qp4A76P0Q0GDuk02ZQYKcyzcAabS4sFbd8ly2f4jk83DGUNMB78jS2iuFjJUsugWBdqjMlXoWHCtgH1bXi728NsDrxsK51bnYT4js++uDg+Q9u5szB6ykk7LwOCMPo6tHnaUMGdsK0BMGFHz+WwsHQNPOT4btLfdMFl9+fUUgLPrQSBUVdwQj9hAjC+45sRpGE9/nTYCcEVAOx4UScHmjgTa+T92P8PGjK25TkxprZ3MK6LR/4DVU2jd49WfWckORNibdv2tNXNQaEYglZyeFzX4lJ/N+YH09Ft7UwtHqupR0NnOslSyK2Hj5zC9Woch9T5NPIrFEjNzPN68j/IbBFo3IQg5lvCjZLMzIpLjNRa3sNkk45wz/npbZcSt8AzDzfkij8KQXGkAqcrmdrc9/o8Q9RzC5UssIBsk55w0SXKUSza3kTzMxNRjSqXBgH1z2Dw70YnkFnXmDY2lOyoYgQfvZ5wGMMM2BpXarKL47KTfLgf+hAD9Ww/Lhn88Dup1gU7Po7nc1WauTuIXUJH8ojma5L6GIWwtqCT0LrFvHSixIpKprwbH8KiPVQQ9Fe8qeerx48ySEjQrAlF+lV1YbzdDogAV8A2mPNKcBrERCIHDWC1N7r3Xxh/o5kin7QrBD63BiOKlZX1vSLJfdC9+/lEO5tPk3lAFceZcaGAgXriiToGW/dGiyx2mKXS4skWSvPXxbMx16aaPJIHFLR8YcZjbt45d8sjpOyt9WEbWDT1U/CoMeBLYxNexegzT/RNo0mY+LeO1fHzGI8VW2jgqK/ak+PkadVBpveof+BZJMQPQbP5EVkReRDZIZ8xKn5f9YSlPBlrM3Y8HNBegmOcIEMEjSOgi+3SbT1oHtZN52EWK0SC5HpMOWKNuZBTslZAzefPBSQ9mYUr/BjgGp3aAxOOVTZIKWSc/Wvy
  template:
    metadata:
      name: cloudflare-tunnel-token
      namespace: cloudflare
    type: Opaque
