---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-tunnel-token
  namespace: cloudflare
spec:
  encryptedData:
    token: AgCWh81hcjF5zv5R1fafuXhmZtDhAK8MeamHpS0Nj7/XCBKTFdSocpBX8I1aigDp+ewjh/pRf0cQNiaax3Lktn5wAM0psPT53v8kdr1KG3mgEfOF7k0NMCA0b+a7IAOMT9lcFDqQmllva1MbXrN+G8E1/LlMqdDNcgdLNvy7LFTUsGl+80NOvWhe54CqHlUv3+6fNW4A0dnueILwaxBRGPLbCyz4+MjaJWZ4niATw9DAegNDzrvd7mZ7RQUNSnv5BqW3dL8EKFGtAXp4AJ+fCKeszTh/TsD6h69J2mfUHjTuodL4Rn31fvvjP1jQr3VLhICecBT63U8RjvBGZ5VhH1K4VXMpX9ayh+P1Mo6yCwiAGg5q1dTlosLzU9KIs8Fw4LqP7kGPLTOjDWuaWXnlqhAl5iIuN85ecPVuJpyFsSq9l1+euKY4DtDzMMP7oZlCVLKx89nW9lDtnybybOjFstpoY1HM/47Y5cD6U+N7NU5zqCrQazVujHLeO3RJxMGKgdH4z8AksOX4oVDDmtWun2HKiYQpFjIE7ThsiEDyiqCm+vcCvEBKX0qlsydQ/ZQaewHGZSfOCAb5YScPXgwr2ABe1jH9vFHRMpdZH69XDNMmTFVwKBjMm7JYxPXktF0KMuACWnC6YUk5ofW3GdMNgE+YreZPSR04ROvPg7KPSEs7x8DtK9nQym8f4SzdHKKXuWGC7kqWk6J97cKAjbnRNBIF+UgBcFfx+4t1y9Lx40KoyzbS0cV8J7uzsC4Q/It02BKbGViOmJbv/8+sCbXRDG2Vl10vtoajk7+8+b1x7VuIxmCy8t6pK4yte6lwX8KUfrq+S5X3C4o/+qVf5KnfwV/wc1ja/kmipslmYDCZCKwPw2uF7aGzOtDw2xQn9jhdOGYtFnEYIyiM6+k1dpFmthldyoMYPz1AjOfyDsWStaUH62y91BNu7S2f
  template:
    metadata:
      name: cloudflare-tunnel-token
      namespace: cloudflare
    type: Opaque
