apiVersion: v1
kind: Service
metadata:
  name: cloudflare-tunnel-metrics
  namespace: cloudflare
  labels:
    app: cloudflare-tunnel
spec:
  selector:
    app: cloudflare-tunnel
  ports:
    - name: metrics
      port: 2000
      targetPort: metrics
