apiVersion: velero.io/v1
kind: Schedule
metadata:
  creationTimestamp: null
  name: full-daily-backup
  namespace: velero
spec:
  schedule: 0 4 * * *
  template:
    csiSnapshotTimeout: 0s
    hooks: {}
    includedNamespaces:
      - "*"
    itemOperationTimeout: 0s
    metadata: {}
    ttl: 720h
  useOwnerReferencesInBackup: false
status: {}
