---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: nextcloud-admin-credentials
  namespace: nextcloud
spec:
  encryptedData:
    password: AgAPEySWHsdJS/BmdBSSdNBwc/IN+2MQFgl7PVNTWx8780B4IQmZxlMRsOGi/vjlr48ZvjmvJgP9uDTcdEcenpilnPK/FubFwaiOQ7Ldff66rZEe4XgqcjKYK4Ss9XoKl/c9pQs/Znr1Xee/Tm+tzXzpRnFrtkM7vIr7rBbmtsnppnVgGkQcaaHDvNo08rIVMRYpHHbS2KuX6JOMA+bpKtHanqlnT/HR6OwbMlx5zIUYew5ohvBRH68GcsBl866SjqexL6GP7O4F0GxsAMa5jzBYrLjL0j0EAbH56J/uo+EzRZQAIu5/lsJ2zGWy4ogsTh+mpcPn7QWbAJvSfwh1AxaBO/IQ5P6sRH96Bcyrm9eHYjuGrfur4Fw5zuTmvW/cu86dcHv+4+vSbSfnf55+ApSjNS4j9d96kC+8PBQ2xh9yXdYjm7+NYQMFpIyOkElSYkAi+k5SIPLfsPKVG5tu919JptpMjSSo9nJ4+PgsIkUkKk7RmeVCJtfJB46mPmwzRUr7tn5Ey+mO9+MJIFXkPbkgQY4lSGCn20HVE7iJTn366B05hWmYkiRb/xwcwIf746IbAw5iNHMjNt+5V4KdqNzJvKlOQWSs3Xsb+3PtoC6oXMZSLpjuFeIDMRNBTn1yhc8r5JiZr/J+mdnaT7Htgzuxe+mhsgswVyGGmBsqum8c2wY3JId/+2wAfdMSDeVjR6PCf9+vicMV7blH6Pu2JBExfwSRUVTvqLqufLFwswKZeg==
    username: AgAf410wHmQoRF0dZ9tD7pV90S5NqNU9BXkPGcHpGWkXekeGAi6r+yfkxHEAId/ipr6FEXlmUk8mHE6fjAsfs89UIc7Spxtmbdgv/tNYkQSLSdnsPk8O5dG+NfM1GNdPhlxvxBtcr7L22uS35p/wHEf5zZe2WZ05Kghuih7N9ByeYaNmw1iehN7h22LSCBODYzGOvoFcxuK35nku4di+YAZquxzqK6Uz2GvBCjSoL6NY7oZ8f3beskeqsIGfxw1eGRExkSpHtaOpxyDN1sUUY+RCU/fQ19LV9CBemsQJDZ6/yU34wPFArM3xmNwRMUuI2DVQVFbev10AR/cyHuXcu9c3jGwQXJUyXjEAi9u8bBYxL36JcumzFzXjFXCd+IeteRIXa+OthqviafQC1nOKkETX1sg+XG4ntpsMOxpHoHwLj50yDqa0C5MqtwmldvpeAog9iirbEnXoqJsh8wzKHpgj2De/WzI95r7rMCSLTYRGfRju6liMcU5LMoNZgBXhq7ERK1/b/UqNdMuhPE38sYBXlwSNH676uxQXI9kOpBqIkZSYgpMrUH8UAszAZ1xs56NykABJZScMTJB3W3mQj7NQ7681L37wk4qlGmnTmAHZSCdskD2u/jKvYS258G2P7qN9QpPzOiVDGJpzT9f1LzgNUNUPC6aG/U82zKX8OG9Sycoi3clss4VT610L3iysqE9gKh4hHA==
  template:
    metadata:
      name: nextcloud-admin-credentials
      namespace: nextcloud
    type: Opaque
