---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: nextcloud-admin-credentials
  namespace: nextcloud
spec:
  encryptedData:
    password: AgCSlHqAmNIbTMOZzrfzLHrTAAwbWGEHITZS4RigKxcjfhHEH3MfTLv3mrN6Rv2UIXLuAEiXr0BzY4CJL0Ef6JvKsbeKhSn1XostWMf7PVErW7c6Yy9Y9pKL6zt/foSUXaS0c7axiqQAa4Gq5f+KxKzUBFveYyESVq9NrGVRLogwvpSyO/y4/HFM/8YBV6IIaAb50gNZnCiCaFl/MR4xRrYp3ew7DpZ5dySa5Fi2kYbgZOhEeuX7P9V8IG8vt8WlCoL4175QcTPgbXD0865Qi0KQ+I75kMxAog/D1HsBJH8jEnekFq2XzFk0lDcy1KvatMIgt9O1HyE4vRSXQJXlQBtz6FFAnYaLuwxRb0vwF0N7E9nMgI3Cbzhhao4thKvSr3knfjZACvUEH8jJMzTQ4szWfCjMeM+K/tpd2ncrV1hifUEnDDYRgEENV0Dfvu2pfitcXFRhSFkStYWY43kmnlho6RwR8/Zw7M+GzzOZ9PKwfgV+74PUX3mt+nCE5F6akeW4BPcN6IrzUzH/on2rT0qQHikOh3SRTftdNwJ50BHzYBAjW0ERIBIAlLiBfy/3d2di4Rr0WS8Y19T3i62kYGr5Ht420Hu0f51TXjI4/tQE5yuXdQoOeNU4c8aP/Qev5x3QiORlmKB2hZGzj/V3PKTbW1aMNXO5hayYUVQiOzZnJjIfFCYLwUJS92iL3bbIMoXeervhKshlsM5yhhh1yk1Tto6BqDNWiBpKNKpplkpHbA==
    username: AgAlm0oC909r2bPisMtFzVuRpEQPAb/nutGe7PFI+TC+YgKEGaOXM0qIYxP9aDUd4sDp5JsSXmhd/ltZp20gsBppWDT++TUYDFIepfZebi6GEp1PBR6BuIebPqjhNDOKTLLvXRPVox5cGc2tMYRg57VjbII3I5lJMbAus2rK9A70DXkFIJvlxptOSnNNCTD88psSWhd/O9zHRsGmjOfeqD2hlHcpfBlCj8pYD/6E9OaLqhc4xl9tka8Ucdvqp/t1oQe60ND2Zbqxlbwc0IirKL2G/i1jlTqyQYe5P0f2eIbJy/eDUgrfoFhaXUHfnfzOZA2U3+mqdcGCCL02vpFIaucowWSWs+AdxrxWxZfz2G1REvytPQAeTUfIUm4HvrQ2a/6JJrg3khY9RSH7fhuuKn+qxQVQZA1FV8+4sxWADMmJYsMYVz3NzkicH2ssyz8XtIKrjOYBE3lUBF4wxJ7Zm0Vp3JYwbEXq8SskqxJdoEGrFsGJOcT340G2roGuqfQBQjqbTlDanlrY6cjkFUAUXlkfuAmTf38d8lCuV/VO3Ycfsdj0J9U1J6tkGxvpJAiUK8FIGCSaEMBnjbBmrJiuuiS/2pP0M33C8m2TqUN9ApJMO2xnnV4zXX3B2HxS+rWCJ+Tq39a1rTUNnAK01Tq7LXTeCxd96I0qudk0Ldyjllrd4o41i0pnX2wyBXpEElrXLpIfFYzU
  template:
    metadata:
      name: nextcloud-admin-credentials
      namespace: nextcloud
    type: Opaque
