# apiVersion: gateway.networking.k8s.io/v1
# kind: HTTPRoute
# metadata:
#   name: nextcloud
#   namespace: nextcloud
# spec:
#   parentRefs:
#     - name: homelab-gateway
#       namespace: envoy-gateway-system
#   hostnames:
#     - "nextcloud.mateuszledwon.com"
#   rules:
#     - matches:
#         - path:
#             type: PathPrefix
#             value: /
#       backendRefs:
#         - name: nextcloud
#           port: 8080
