apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: nextcloud-postgres
  namespace: nextcloud
  labels:
    velero.io/exclude-from-backup: "true"
spec:
  instances: 1
  
  storage:
    storageClass: longhorn
    size: 10Gi
  
  postgresql:
    parameters:
      shared_buffers: "256MB"
      effective_cache_size: "512MB"
  
  bootstrap:
    initdb:
      database: nextcloud
      owner: nextcloud
  
  backup:
    barmanObjectStore:
      destinationPath: s3://mateuszledwon-homelab-backup/postgres/nextcloud
      s3Credentials:
        accessKeyId:
          name: postgres-s3-credentials
          key: ACCESS_KEY_ID
        secretAccessKey:
          name: postgres-s3-credentials
          key: SECRET_ACCESS_KEY
      wal:
        compression: gzip
      data:
        compression: gzip
    retentionPolicy: "14d"
  
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "1Gi"
      cpu: "1000m"
  
  monitoring:
    enablePodMonitor: true
