---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-s3-credentials
  namespace: nextcloud
spec:
  encryptedData:
    ACCESS_KEY_ID: AgCA2H3Y5I9Pvar0OLK/CZpwviUDsLiTEQoziDN4vlQrdOMkH/0qbqGUbhI9tB9g1WGib4s3Gvv0ypnWrhf+nv5JlV0++wGqFrgnZlJK/89GXwkiswXUqo/mkDVizaDQjyvfNCvjf90gp7hhhyDjy6Fh80zYz3mXknTDs4srfnbVHLIOL8tt/EIv/U+5FjlP3axN8Vm3ym7cVYg/ZR56syljR2otJU1oMjiB8253+jADLmejX4lUtS3wfALWxrNjpXoV1lJF+t+JYBAmlpP/4S6U9h40ku0TEc6N2uq2LpGAnEKoikYs1LYtFq1SDDHSBDq6nFyLm6wklUpGF+CjnRRe0+fcU2V9JJyUWjA9sXNj5AShfAlGHVaQViCO6RV0EMlXTqg/tw6Yl76XT72IbjMmIUiDCXl1Ll/MGEpNoNaek9Wc0NiabHTWkA5MDhVh0E2mkDANB71tSb8qsGhAoojmPDoXzylnHD4mKt588JzvZ+JG+IqHZcS7EYwlidqPOhpqXGG5t2nsW0O6lDeFpZX6Ax41RpckarfE7tc2THIPVSTdvQ1x0PFzpdfr7WQfTQPJVaBkGbeY1rmMqPR0jFoZG0YjTBEvp2lbkdh+NJIGkRhbY6dPavIpXyb4cGamQoqwzk0nqhULS6W+vlQEtloNGBZ0YVk+ORkj8s85nWeWA7ovVYBoMqOEePqZAHjwongBHOGlgoca4aqei5P24tOkaNKiRg==
    SECRET_ACCESS_KEY: AgA8nClVeawMp1bXCz5bqaYRL5GQj9J1DPb5PXWYAH/nQNIwmhusLu2bArORIBd+ajp25+Vl1jFDSjSBePXkxChttbshDHbdYOIviD3qRa/LbPrV8mSjX/yNm9T/kIZJFKsVQxmEVKqKCohz3DhnxWyHZHvonjisSs+5zbRA8s31Ysnx8FgPRTKZ5S9Z/4zBZC0LOkfF1TJ8EUg5L28yZQ9icdXXUH6RSdUST1f/PI5QCv82n+L6oCzVX1y+gp5j4jEaGSn2dJYxDCo6q6Egz0TDyIUACW6E2QD9gsrjEyi2cIyRbZBUHP/03Gl20v0kg0EEXVB8KGZRDfdSBDBG3jUfZQA8VE0cBmm70zVzE8tdfKKCDLmoH1SAlhId/VEhD9gyKWBc37LNfSh/Di3keBOsB+i505PgZw7g1xrRnP0fmZ3ncRVqD9jzFId5zHOeBHDl7EWOUaAQhDlenvMDYQZUFGw4oCMvBUQcAiWxdwuIcW1tbSnNZ4xd5GfzP0WWNdnOrBzlxWsMgd+nNeP4ip5I2211iF9SKlLpYQUglSGZVkyZJBn30wWQVEydS+IgODzeHJe/zaBzCq05fbaWLdSH8zmGxptcmn87IuLPcLPK+ACCRaRn5xTlpGLSYLzYlmA3pigHj/KI61pjCJ0yhrdHRln6t1Vtu0yKTHOZ8w5KzWXAs5FQjhBgzkICl+BaRX/UAqD5jEtDQkaoy64WfsDXRyzN1P5WAT/UsdbbSSA3AeC26HJw0Fxs
  template:
    metadata:
      name: postgres-s3-credentials
      namespace: nextcloud
    type: Opaque
