---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: nextcloud-redis-credentials
  namespace: nextcloud
spec:
  encryptedData:
    password: AgBXK492D6cCGRH+MEpMmAJ2etHlGL3zXPxhdpi+0WJrSatVMMvbwl3AkmZcWgfnj1DCtFXV7/bC8lZ/xf0+0N9jj3k+w1hz/dTiM40EAAqc1sbiTJKcJrbtmCZ9033nb4/S/aVCZdHbd1Z3+L1ghhHFkkmZIIAAA3N03dX+aA6OzD58QBWPSM8aPqWo3u0P234hawVrC+YfS1yjN3EPhWqvmVTw+oNrLCKK5rwgKbAYzbMcRTJjUe2vymSvHiqqlgulZqXbBaWZUmaSHWSNP0sGf3UjAdtXyiZQUbOj+drP/Ch1p1c6dYw9hM4wV9njuTNMX9BbyoGtQJCwf2REJ5M1dhXBHQOEkIU3wQRr/kN8TBAEQf/Kqh1TzhUSkWNO1XJqDmC0EPiDlYMxxgvtUCrR1kjRK0KEzBIyPe9KJweGtmJgUg+KR1/4VWCDuGg2ZzyQnw2F4tWHXZnFWc10tLjm0lVZ3Q1Kxk4Bv2kNJ/bpqA9RzLkLyoOl84lQqqSvATu8dMvgkEopDKavI3xCsy7cijt94KsMk0MHQbY/hB3mGE7dElSA90phfsnn6gIk6uBuw4qJ2ZvqO2TNqygvwHAIUXmkb9cMp0XXk/ufpTgc6j9RWC1Nvge9KbiHIW9zahLJj2hNuc9utDbfPpcPuIRNhArP+sUE0sZ4rJg37V/UVKDO6k9h1Zzfh8X3jxdDp2Kyy6jnVuu+zEw+MMAKxGXLhO13eJFXLnwhRJONZZCO/g==
  template:
    metadata:
      name: nextcloud-redis-credentials
      namespace: nextcloud
    type: Opaque
