# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: envoy-gateway
#   namespace: argocd
#   finalizers:
#     - resources-finalizer.argocd.argoproj.io
# spec:
#   project: homelab
#
#   sources:
#     - repoURL: docker.io/envoyproxy
#       chart: gateway-helm
#       targetRevision: v1.6.1
#       helm:
#         releaseName: envoy-gateway
#     - repoURL: https://github.com/Axot017/homelab.git
#       targetRevision: main
#       path: kubernetes/manifests/homelab/envoy-gateway
#
#   destination:
#     server: https://kubernetes.default.svc
#     namespace: envoy-gateway-system
#
#   syncPolicy:
#     automated:
#       prune: true
#       selfHeal: true
#     syncOptions:
#       - CreateNamespace=true
#       - ServerSideApply=true
