# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: prometheus-stack
#   namespace: argocd
#   finalizers:
#     - resources-finalizer.argocd.argoproj.io
#   annotations:
#     argocd.argoproj.io/sync-wave: "0"
# spec:
#   project: homelab
#
#   source:
#     repoURL: https://prometheus-community.github.io/helm-charts
#     chart: kube-prometheus-stack
#     targetRevision: 80.13.2
#     helm:
#       releaseName: prometheus-stack
#       valuesObject:
#         grafana:
#           adminPassword: "admin"
#           persistence:
#             enabled: true
#             storageClassName: longhorn
#             size: 5Gi
#
#         prometheus:
#           prometheusSpec:
#             retention: 7d
#             podMonitorSelectorNilUsesHelmValues: false
#             serviceMonitorSelectorNilUsesHelmValues: false
#             storageSpec:
#               volumeClaimTemplate:
#                 spec:
#                   storageClassName: longhorn
#                   accessModes: ["ReadWriteOnce"]
#                   resources:
#                     requests:
#                       storage: 20Gi
#
#         alertmanager:
#           alertmanagerSpec:
#             storage:
#               volumeClaimTemplate:
#                 spec:
#                   storageClassName: longhorn
#                   accessModes: ["ReadWriteOnce"]
#                   resources:
#                     requests:
#                       storage: 5Gi
#
#         nodeExporter:
#           enabled: true
#
#         kubeControllerManager:
#           enabled: false
#         kubeScheduler:
#           enabled: false
#         kubeProxy:
#           enabled: false
#
#   destination:
#     server: https://kubernetes.default.svc
#     namespace: monitoring
#
#   syncPolicy:
#     automated:
#       prune: true
#       selfHeal: true
#     syncOptions:
#       - CreateNamespace=false
#       - ServerSideApply=true
