---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pihole-admin-credentials
  namespace: pihole
spec:
  encryptedData:
    password: AgCRQJqhiyez8vFfsw4lHfytSevRhSJC3zBVuZ3v8YSVo0S7vz0Zq6xoVt2NE4rmCZ4TndLfWOT16m41yC3KqPWI9CgNJu3Ls1f9zh3zCQ/eGg8B+TcsmzTcFa9G0EOxviQEmKH9I3k1inlP2jKIEodLwfnhKzosCTImTjTc4OXOwGeIwYWQ170aIovQNR4KExV2R8V5N+eYJ2bovm5FEkjEaHfTJI6wfq4Zy+lu+lvaWCNFM6WjW4fcsOUvEvlLr3Gax2NQ/5kzFh+yz+X/5kW/t4FGEt+yrJdi2mcgstc9fboxT2T8C+ZqDqhUpBZaSkkN09OiJK8yzZJKZT/+VtpLmQny2Ms3RYFoweM65TCC9+N+28BKngy/2yrSIm2UG1HuuqDUwBbc1Lui9D/C8xpoMEuq7dbMmYOLxH9NuNAKctpnlS3Sgt6SA3lFdivD1PMkoYWXyu/MAyAIZeFfkybAZ4IVsQgea9beCKCEtI9JabePKvr9R5BZeb448T5iZwbPORsF4cc/0n1Idit2QyezLnM/ou9johDrQzxjAXcOzZyqMvVaZBqhaO2yA2Idhcjgpfflpkbh2xW0C1D5sDTHx/BorqRCQ7K++fAPwVu309HVlnMI+m1dDSFZYOFXWPmbpfVhYRbXcRqHriRmshY0l+QMJPppyFuhCGu4Ijk99LPHr2WtLrU2yf7MmdVBWN32tNmqqbm/JfT9l+Q42od6n3KrUmPFUZyxV81lky40yg==
  template:
    metadata:
      name: pihole-admin-credentials
      namespace: pihole
    type: Opaque
