---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: n8n-valkey-credentials
  namespace: n8n
spec:
  encryptedData:
    redis-password: AgArTcD6gR7cA+kc/ocjJiYiBTbmpOQtV5T1njdxSU8+FrsJyveIyZqe4rJCTVlxsFh2y0EQi2g0YNzzo4Hq8GH/IcNxZUKYkm2B91GK/XHNddSJhtbr8lNFDH575PQFbRth4qVrgB+BxA7/C4jmHZY5M2jEpi7xyxMrIEukAVABoYOrEnh3MVXzPgntwQmuWkO1kIOOuZLr4VSk1hlD93wZI1zplkI+wDZO5jyGU1KzvoNzHpNYqXCZ5xwfA07wuFOXJLKnMQSO2Wm/iTFR7tC1t/QiAjVz979kOeDPLIXVGEKeCIZTTy23QUxEB9sZ1Ep4ZnKadG52GfakqvB09qOE79I06GH12BtaLrO8RbGEBpO4M4FeqbuUAst4GEZPVcnFhz11Vtd/LrkeJmlDhkmOWIx3Ts2rmyE9jiTW8Dh6S5ZfjqN8xCydvyq48zz8rWOLEePD14Ri5v13+V0JKOcR+4+5fGpazxRTjrkOexTCIkuV1s3zXO61Cl4qfoYj9kqwZJH5LNkufej/yior+1lLsg2nfmyqWLvyl4Ll6BjKfbEnHv1gW3rXwwO1amHKClrc/nCxoyJnuonvvUy7aWU5Y6UM42PZ/EXqDBl83u2V3dBnmJ9cQr8ny2Zt5NzI0YflgjETI4pskYD1wr3Ox2g29bXVxrpIEkcHJmNGVy+3J4XPF0AMddYPCM5eiSbFWNgDWF83sbUAz8xKLVMKtkuy9D8/wI8foKfhWMmjNqLMkA==
  template:
    metadata:
      name: n8n-valkey-credentials
      namespace: n8n
    type: Opaque
