---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: n8n-valkey-credentials
  namespace: n8n
spec:
  encryptedData:
    redis-password: AgAuviugbJjDWKzZJASH251boRQ4xDHQx56ycN0CquM1Dgfspm9XVDTK5gXwW2m2uhD9CwBERaBn87ZAHftGDuTxY2cSNiYSADJbdb46lAXQJ6s4UvxTikAIqiHbtHsrNT/sWN0bHfYvnHL+Dmtc5tRT5YaRivyLpGYsQk9ioYmT2BNMkRTYZL39t1bDQbUYmxdut8ejZZxtWzyVANCx+uC6+fpDstM+J1Vw39Bw61+6ftUTgEYXF1Q3LQnpr9giPzaydUmglPNiAEoqeT6PQpWYW1vWQ2hCSpy6HVCjzEpvbaOWOU0r2nq47AkdaO4n/XNfNcE6SxbgaKXoJNghSiLOt9UzhKmMYgTpEtVHjLSIpsuhfoC+QtjMoIl3OJlHMWc0jSUKlhwDY1BQ05VU8i0v2J6gl5GYN6zpfKue33zX0qiFe1tHOB2w2yQAQFHPVHlGFmzt8Q0tn3QW64wmlsJaxp2el2LJIQS/g80Qtf0QH0V80vwFe0khwJThd1Rbzo1Ge6VX5SQy1WydDwoOzylmS9kKYBNOeOTK6QifzY/XN1EeBJN+VMWmOrmPHp60haBQaF2up1QciBKKC/Cz/zaFfHNX5WKPaLQHM4P4KHJ+p2C/OcWC/ZRU2FAOJHVsbrdzNBXIeqlg8OnER5a4Tomnn5vA73CM9lGUWyfWD7BNzu2+vtySXD3Vx1MVbbSqdw+3ClW39yQXD2L6P7nIxFpHCFTwtFNel1EtNKAEFa75jQ==
  template:
    metadata:
      name: n8n-valkey-credentials
      namespace: n8n
    type: Opaque
