---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: nextcloud-admin-credentials
  namespace: nextcloud
spec:
  encryptedData:
    password: AgBGkJQH9KrNeZbve64hLlvwhUUan/DgIAqmIFSur3B77/EbZfRWvdRoby2PaqPATHmSWJVDjmTXL3QSUQ34P1GQQKO5VIXFeJUI6wdebOmSXIUeXHwdhlZUFsQ0DIw5VTOG6ZcyU92u48ozUYcirYkiwIw1FgMdwSkrPDKLyet+L8SHwfRFtXdb6NIn8udioLUJfv1K9Sf+KkYU7oGiLCki2jRXiZPR7bZuYYxmO8i2EytOBrwE1Ku+NeOSVt/2+vYLWSCOQ9RTpx2wV5ULo7p2zpW1EceV8IlF9OuJaJvrbiU8V9dMVHSqWmq/nVTLdKUJFyAJSXLE43Ij4VgxZp7YakYC8rATAJ0KcROwJqGm0J3FrP0+cMgBuv6WpCyPPZmCdEw72SBnickOifkpdHeDfHmbAVLZnXzYA5YIXbRwFgjYlTduk+OLJsdicOGbjXHzwBnlEz0NNoEBWZAYbeiyXSDEt0o5tS7RtHj8yJtGu2taYMgg3Qbm2Tt754fcFDiL+WRQtGhddgzpGhg/X+fNr8AGDbCpo9j0smShVVV5NaN81jGyCWZVXEz6SAYDyo8gvDu8NP2prZafW8fwCmTNcejlBTgQllENoUEEv11Ty/Fr8GdBDQmy1obhjV/1G8R0hGsT2o8MF2XSQx53qNi61gLn5tCUbIYFBS7+iJtivHK57+t5MzsuLKPbeJta0hrk4KzKL+fyuP+OMVOiePo7XOSLmBAdVrVQ8H3Vyl7tk52Rsy5vGNYixy+eA3qimcz0/P8/dqDAKtKQKn/7i7HX
    username: AgCHJhuW/M3522n0Abn7v8ILvHdJnLE84g9+ap59JajQct1wLCQT0OPlcpfJeqoeEMCzZZfn3bBVQQ4eFatz61ptfyFCkZjHBw975W+X378UQMT0N1+eIXEhiLe/91M97lzr6fDhQdmgsKmM6UtEiMLBDpJ19Za6tLD7m9+bd9FzahR0Wmcb2ikvFHbCS+H5lU2SZhPZW+Xlxsp1ExVATezcDScM9SahmmvRzOvvUDP/gl5+BnRnSnr8eK3zW69tfSkku5IAG08yQAix2FyqWIpR0nSZKWTJuJmi6rfUg9oM3d958+xb1ISm2lw7/81ToV5KT6LvGrRGfemOvdXi1iMuzMiwLkHtj08vSIzsO4R8pDpi9GBsXLoyrRcdYkVVpDYfSxEUH1AfwxkM+StCWEvEekZgOAXmGUZlG+TQ26L1ylg8cLuGDfc7fu/j44QsyCW+P3Cz3x2OcsrNsmrLtwOnBYBQyrsBwnptCxLgh7LBNEUAOsSMwTc+7QFWNHJvtmFnNbTW6LgDFrQHk4EBUK3AycpvJuRDQIOKy/6JnjdCnKzOylxXuZ70F8aiqf7AkGjkFRARl3hvKFP9vFNz865OOpuM92BbhZhb5UvUmrVN9dlgVQSIRGKL3Mex3s3k5N1qFBdHn5FOU6XG5UcCQ3IvllJ5Kyk4iLchKx2KF+K+0UQXF/3iKaDsLBcNysPQrzfXoA4Y7w==
  template:
    metadata:
      name: nextcloud-admin-credentials
      namespace: nextcloud
    type: Opaque
