---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: nextcloud-admin-credentials
  namespace: nextcloud
spec:
  encryptedData:
    password: AgAJ3Jn7rj/K77+NDwjROtI9N7mjX2ELMCzJ2YD/d6T9K8Pk8bhCqXEUGSMyqevmESNtPgPkZkKP5g7rSqC9W2YOSfJeGwdMiG83fbroq+zYjjxHGl3qYc7CFZHqtzhTiGOfur39CrUifjlTeyR4IRrH9rsEOTqssUT0bWsCmLHfCINwhZkibjNwUBAvZTM1gLwInnihah+kHYvgIy4NegD9e3d5dIvW//DUp5jvUYSPDo9WLHt+V9bGwCjZL6akKmmQoOqKdSSCFNtUT66cZBmB9PtiGJ0Hwrvj9cZZBB0UMv3t6z0s6i4NPY2jHJwm7fheDwfiSV2J3EUuSJW4hol9P/m5Wc4Q3o1KLBslU9toBPbvI/pQSIQ1WooJjyRIxySNFQPPJzo8XblisBzfLEaaJEUecMIO1S8N8wl7pHXQ60SN4FLbMSEztdVUpIca0S1nNyxRGH8YEZ3OcY3xhvP3/s0g4VocoWRm13R8LlfMT2CQa9WXW4g2Qyqnqzhm16qp9GoPtdfw6KTHneHF1T792UCjHSZCYl5F6W+ldlFAveJmZV+Hs7MaeVuUjxcfnH0F4gVlSfZZqjqHIql9TADKEOMIfm5tSkeFbNJMH8R6cHlgehxtEAHLWVs493GphV3ZHw8O4OC2UYxEstkUcW0VRi9OSPXLX62ksSsJxv29STk/2qOMZ7o/xo3N83gH13GGwN9LNA4gvMt92nrja8I9iqTZPfIr7ayaKDXNWk5Lwg==
    username: AgCmDrn9jRbhrNcRdqs/LhqKktHTwx9IbCrCucbHqe0d0nuz/L0TUJy08F9u5lTn89btlOLCA5vVsOvinuI1GOjvmVRobce6dywciHfJLdePdk4Eu9Pz34ODGSkR6luD2LcpMdF1WL1S6jMKFyjqofhAHJ47/qZxoAeOa1L5ffQwKGsmagCIlz3g+ipc6XbG0Q+WkaROggtjYejH1P9XmAWfDiaFGNOWMmTJkFes/srL8WTPpLAiBNWPEjsGzNYIRaKGJ5BzDGNf0oBYDjLcwZ4PeCTi6nfgxTto0VYuQBe7Izq8PEXgeFlemashoRBHdk2SkAOVocbXzZJ5FHk3vc+ySpldf0HLIalUm/OeFfoBu4yg/0JWy4uBuzq72MiQiVlaiPoAb6k/iabVkrwhpOJJvvJf1JAF2S7OvG1VKdpUYqBdjuK3aCHbDn+IxqIMRz/aeUM1aWqFjxxjT6XZImXml63ECWU4OynKBy7eM4d9rCkg63FqZ91RhhtWIDb5tEvm6Owj2N5Y6DFeUzJDYpyGnxuLCUDK1J3FdHhveBnJawa9XZ/II3Vj/RrBIjwiie8i+ILmD3j+/RbhQSZjLgchDSjIVpVFkimsJxfgLSUQxjunQFZj0tbLH2jkVv8rVkgln9uDAXd0naEjHfz1YDHBXWQi5uYsCbnqE0msCeTRTVDMum2IvhzEwV5r4JLgEKlqzlN2lQ==
  template:
    metadata:
      name: nextcloud-admin-credentials
      namespace: nextcloud
    type: Opaque
