---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: longhorn-aws-key
  namespace: longhorn-system
spec:
  encryptedData:
    cloud: AgBkwWQ/6IEio/NhuWLeDHsrtLUuFEpPXaG7iIj14sVWgO1znTmnJbCCfpuK0EpIxO67lmhWUTXOlc7Lls7u7K0cczLWDn2RauaPjRIsPyA/nHmdyCSMNqXZhStGM9buLn7YafoRl1rlV9wcIojyBIgGH/jXAvXp3VimOTclzhqtWKrYtSKf0lqsLw7l8Y9GoC5RiWLrDEOpTNT1MhnUqwnp4tpor7aWOUMdDL2u0TR7X6fRygSKg7DlVKN0q6BXwoZ8i4C9WVXNSty8D43i7eKvF9qkwm5zHRyx41yrWA1wDjL/VmVfZvyBeRKvyicg/OR7gqEa9CGijdjIip1sa2ccz00sIoHPF/+tRoCNAAN0Ou1IlMS+55zBT2zoklXRP06rlqvE34lssfni9z9Pan4nqszlob+R/38KmafZB3DmiZtwMoOAGaxEoHAXgChmr82jF2R+g+7K1er0PciGtoURkcZPxakAsUIfHBbPVh59ALE2DbWXcxrvRtkNooWbx+N6KAXxayrQmpYTDDtAwydGe7PWK05Mn6J7vBvOekrQXhQutLFKrSzoHDHjNbevu8YLjlpBi9iCM6HSm7fukTT9Hq83N1NFKGpwZx7ijwBioFXpyWIqYpI8+8WPLxAmMcRXaJ49v+1/pDw+NIPrF4lz4kXsx+bI4hMvzyRYMhP62Oh1w6vcsCookK6b/LaGIGuiNrhfwTLdJfG5nH5zG3B6QT32H0OpRA7Dz0X9uJzHrGm4vQswEAtN8czu5HVFFAwJIcL/zmKhSrAd0jEepyvRh5vnXo+6YD2JsIu1GrlpUcm3bgJdqMNfLAx0EeO7DZTEL/52nLGaISFq+P/kerIL
  template:
    metadata:
      name: longhorn-aws-key
      namespace: longhorn-system
    type: Opaque
