---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: longhorn-aws-key
  namespace: longhorn-system
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID: AgAM8gQgU2umgxzTCdjkg/RdyCA6n2YrzDDBTaxYsTyIRpDeZyeKjTljAwE17MlpeKnrYATxdz2fTHJmnd9BWJnfC5a5Vn4WMUJBM3nrC7Y9zT7rSrviepiz7F4Mnp2xBfs4GPhaFL6XOtszN4MFBkQXwuIPtaYAOIBUEYQRK2JvUIcybqrSKfDxlDK11YmFX0Vus9QNCaWAJvPGjwr2I/CygEWoXOP0OFdYWuZDNoGh9XBh2G24+/2rSXrC1CZ/nZ0F+iAUiyDd7vSzuH/jXJ1ulFxjeP2c9208b/0WlwyyDk2eFe8vVlMcybmhf5dR78pa2Gvm7vyXHdymO7hVsnkD+UyQN6s24KTfefrBZbUB03nowegdzJYhEYlvw94XckuQ36P1HWxxLMGGuWysqF5P9iQPyTEQM1HnNtz4A4tB4a1t72iJE4bKXUZ8iait9rHy78RNfF2EXsJnoT3QmACkt8UBkn3LY/S8FS0xiBAGBOX23eIeAF4B8u6rRYjJTNoTD3y3vmdqnAUP3BrI4eib7Dgl8aXA/B+z6mMent7sXGhWGo30O86lBDFJe7k3FfokwJOlRiUE2L4C04WAx/V1rC+xE+PSpJn39yfY6FSZMFSlxlssY2Uruub9Wnel45fiI/gjEjW5hnzhfcMIEq5d5rp3LYNyzjK/sBVMQU9h6FmfCn1kykpcr0+db5ICZHwtz0QZZALJC4NKvGCGJ9OJyuuNrw==
    AWS_SECRET_ACCESS_KEY: AgAxBKa1huUEpglpaVHVmecVKQjabnXVOpegL5i55C5jsPeEYvACqh6x/qn6awpDpY699MW66QWITVjEm380l4bdBFhMGMS71SsMQ3xTKQTIMY/upl3SBVNDdKef4qiQ4YKDJTHn4Gpo+Rxx5ldVdE/39eMthAyr/soxxO0aFnOp2pSRvjH364qcUQil9XFWINMn4mpJjattJPOtwaEVSVMiimXpcyygdJXdoWBicT5x2zyEac851ERcN2CJU55HJNgZ6qSsJ55wMsTe6YZweYB7KfylLSigXSeKcfR7n4/D22dg3OzwzDEmPZNtOM8zO3OSq6ms32+CrT08w9LDloFpCrsLE+ACyeSWGII6W3iqXzgdnvEqh4n7nzcBaVEtQ+HwvwW290S9ZflrPMfloGZNZtqiy5CVojfi1po0ALLXAkr7irthB7KhJ8A07h06Q0UHUCgiuz9jKy4W0kJ4BAdqo3uFUpVJg7E73/lMkEAPb+IRQszq+J2WqkYox3avpsa+8py2ee1eY48Hf2ZkS5E9goKc3UQ2WQsXir1GZAu9QVfgtsZgNIkIzHoiCfknHmq65Y2lv3zPO6J/THlPnO51RdIQ52dowNr0kgfrrhn7bCGnc7Mid2Cvs+cpsmoqnKzFxJ2ivUrCQUQ0yZ1RKkw6eQJyrC/8otD/FiDzdf9r9E9kn/fkZtRcIy5XLPgYg6EXkfefb11R5mPvTNEdezISeBg+R4PIYXtaU1eeBsrQVR+oJ6/A2Mq5
  template:
    metadata:
      name: longhorn-aws-key
      namespace: longhorn-system
    type: Opaque
