---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: longhorn-aws-key
  namespace: longhorn-system
spec:
  encryptedData:
    cloud: AgANmn/sw+PMZofFMHuhIIg5vKn+N37CJbNvjALL4ro3AgFKYSPb0ThI6y2V461ZWBYpcJ7AiXHoZ7Sll8em5xYnWrmVFRwGmTyoWmosVk7v/NXEu5qqAJ4CVUR49klxRL0H4L16+vWWa6752ga+/I6sgckNbofwHTj2VK+OGlYjqroBdKygL2wGe06Xkrr+jXXeGRd5fXt+4z6sm37AdEnUhhNSlHk4g2Mcfdvrip/R4yZYoEfs3AX827yrL0R6xBu4hEx1QlDo1QILLb7QJj441bLKu7Na8SLoUxXyI5wUV33fWiiNJzh5GMGBkySMclbOHZrww8vNCXzVZ7SKQAPH7CGNyOOOK7QLyhaNg8PCRO/GjomxYP73IRQVys8k6AQrQ6V5qr9DtV/LHv4Ulg9U4tXPcJp94NFld90KAcvBK9+Osj54lxd0KxZjaVkO/uvTNJAxcCl2B02oFlnOTQpKHGyqg/8dG9nHpgHYCev2P+sn4Y6Pyh4/m+VKUgBWd/CVKZtkEFj+/QNXZdi2e4noaZr6H1L46qlF+UjFNLhAjwj80YYZsVQpOgdnvvRKwkhxbycET0qO1ze3VT4drz4pqMh8rGClk+LJvfONfaLGHqYFHqqyu6/jhN1HFnlz8hoUBpz4vE+tbub2hqMczA0vP1NnnYuU8zzPt2o/DBLM5EQuVbNPiYxoqM7IjvsDq0zgpkfzDetgYmji39G6UimSde1swwbDkIcYyJCJ+EA0B9INylmINPRtYx1QNBy8Z+9KNUlkru46ece59k9Jg58l1gZ9Z0NwtoKzw0Hbm4CRtmQ+uuTPczNOTLMRwUZobQqAMV+p1xlBmQoxTnZKLFND
  template:
    metadata:
      name: longhorn-aws-key
      namespace: longhorn-system
    type: Opaque
