---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: longhorn-aws-key
  namespace: longhorn-system
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID: AgAryWHCRjwe1T/RCzUDcNO40cNJCRqzYp7EMNRV1KvU1drqEA8odyMAb2qhgGJVBOq/+J1fNeaMS6ke4YWHizE2BMfM5c+hahmRsU8p8waCMzp8wgzPzMdbXVNSTeRGv16SWnEn3eRMQCvz3q+QJtqCKfb8iLBTA3uCYbHKaig2Hp93AVhKDsDrXZsQjOwI3o87NkbWdy32x7qT0pfCd6y+QSJAnN66//NqKPShrIv8Eqbv3v7JLX9A81fJS17w3i02RSZ/EyZErqMglDw5nUefeoDHcguiKuLeppt7ZfzJu4ktaIEsFZZ04jPRyKUv+f7nXSm5+mR3e0udB9UpaLA58PffKDMuncykecKvkRi9Z0bvG8fJ0sLzLdNxJ7t6CXQtuZzKSyiau555md3uVw9kCoAU7gGNKsLlFy5wka05/TgeIRe9Tb0SzJy+y1dEiRq5UV6cIbU9rIGBpglT/BpQfcG6IdA+9hNWs0Hwmt/GblkRNYj2C3W5AVL/aqsssTbjG50GzgDEmQeY4YSHwYyQg139dNuSOG4H85qG4cCK1WobVGoaNg+mUJCY2yipeTkg+O1p9U39PcZpwmizdO7togj90vWmGiQhLGJbbRUQp0XHw4EbCVqk3mxTAw3pW8GR89XS9DPBcWXsx5Nt8HH0vmJAqXVg9eWpgUlEnh5yGKuJxGnzdO5QQ9k8L9Hk6pYMSm59V/A0mTAOr6wZ5IxsI7k0+Q==
    AWS_SECRET_ACCESS_KEY: AgApsD1wPt8qvYSPJ0q5szPFdf4cxtLOSKrr0DmoRXxIdqbtxkziP/OyDyuNP6aT4a2KDpOjKY+b8yMS1xh0vXzC9UHISZynDPbbvYD6TqiBKrWJiJbrnbotQBQN5Wdhi0mh0IlG/SQWCqTBlHk21LPnt2oj8tG+Pdo5DMpMuHjdSvCKCiVKNuJdxlatnXM/eHKZWgIAtWcoc/jPFCWeepmwJRV7PxV6iU9ArAJyeE9OrCUp/6qluBfaVngMG6vb9Rcsx0kBbIAsdDRCnBDSJXclY22gphstTEvWDGTPacOpCO0pB5c/TZbB5N1my/pejRbY/lAuuw935/RBfyGN7Y/BBpvXKmPLzEWfOQKHMkq4nVzQH/ZvI/MXiFaCSg9v8xlRrqf8Lv8nVtfwLmoZgWXI0fxlaKUt/nCqiWWltOIs9007XA0LgQywzdsZLTorNBlvOcNOSZYIWbJY1l0qLI5bFRaUprpbwLgjcTS6bRrGGOcXzXb0F7MJDNqV3GNlnbd7UjHMWnbcu4BDHLpAd9iFBIp44YlILjsclKSNtwEcef6xRTnzD4//kZ/mCtC9VOX00r9uXuBiLsiP0l6pw6egFS9toYmARcEVZgEVxFsaktWKJAIb7vvcyKlECK9OnU23YFL/ZUqRA8hCNu3qGiLl8yKWuED99DL6MNvJGSRzHTzwcrTXuqSPY+rcYgV9vj6JXw2otxpIrsO9RO/1Lol43xKO7Wy/RuEtlj7SDfGwyHXkm4Nz90Jp
  template:
    metadata:
      name: longhorn-aws-key
      namespace: longhorn-system
    type: Opaque
