apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: longhorn-daily-backup
  namespace: longhorn-system
spec:
  task: system-backup
  cron: "0 4 * * *"
  retain: 1
  parameters:
    volume-backup-policy: if-not-present
