---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pihole-admin-credentials
  namespace: pihole
spec:
  encryptedData:
    password: AgCt1Vjzc+d+ykm0mATVpq1cU1KTH0/Rn6fpGRGKdLaG8ysbGJvJgXMYwsLKyPZtR3E6ikYC3sExKld/g5ogO+QrjX+ZeQ0ob8NBoO/jq6cMZlq7e4SoxTQbYjQAldOOYi98DaaEmo9my4qILL614kRHn3uVij6sw4Uxq7USF9y1S5ft4S1uBHAkSvIBc42k2/LRFerhumc5Pylof35VtoaZ5B7FhdJjnTGSCNMK5KunRFf4lCLxDhiwGUHqOeYfZf0PlZT/rrDA+z1pwdanQOYKLbyB/oofqgslOI3H5TGJuGJnUKdM7P4bgljx5dzCYml0MZURzyKoteCpeQHrA1It2PmG1/Ee5i5S1zZoB+nNb53Zhum/V6WC07W7uv/YDsXShpF+/TjggMTolH4HnouGk4nlhxwyI/+W4NVkqmABeD9U0okutZ1LpRTHVvLMOFKX/pErygAwK1qwOj5Fv9S0L9eO877uU5RvaIkw+qcBn2XP7yUuGX292gwY4ZSkbaxNiI4DuDKg1VAxs72Dbz/CTcQlfZC7J+uP5raTT+u+DqPPF+kS2bb6H/7UL0FMYjvlDUwPI7TizIp6qWv0c0d++LIrfkMIl5BiC+m69RnOGl+XKgrm76y5XovMhJixZad0+Y3hnkzToWsEU7Jts5dZ88bGSkJVEe1iN/FcZrKSi1++tyLy2hyhaaufVta/6Hb4EJNmDQ9XeFlyDanDohHfAWzG+K2aQpb9oSLmzI6g4w==
  template:
    metadata:
      name: pihole-admin-credentials
      namespace: pihole
    type: Opaque
