[env]
KUBECONFIG = "{{config_root}}/kubeconfig"

[tools]
age = "latest"
aws-cli = "latest"
flux2 = "latest"
helm = "latest"
kubectl = "v1.35.0"
kubeseal = "latest"
sops = "latest"
talhelper = "latest"
talosctl = "latest"
usage = "latest"
yq = "latest"
