apiVersion: cilium.io/v2alpha1
kind: CiliumLoadBalancerIPPool
metadata:
  name: default-pool
spec:
  blocks:
    - start: 192.168.18.111
      stop: 192.168.18.254
---
apiVersion: cilium.io/v2alpha1
kind: CiliumL2AnnouncementPolicy
metadata:
  name: default-l2-policy
spec:
  loadBalancerIPs: true
  interfaces:
    - ^eno.*
  nodeSelector:
    matchLabels:
      kubernetes.io/os: linux
