---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: vibe-env
  namespace: vibe
spec:
  encryptedData:
    GITHUB_TOKEN: AgA9Lg21eaYzp5Hqv3YXUW1Sf9A/srBDc+P4VwvXb7v2mV5rAZPCIY2J3N1ujmGSBmDkc4qkTSwGtMtOUgs3dHgef7/JLjQ0dUQ3A3XIO2CM3JvUyw4kn5yMOZuinU7FwoYYC9AE4D6YcOj0KkpmwNgjz4qBUZ7LDPI/MCT+eLF2/ZQqGfcI7bz5e0BV4yhRs/CMc+7SCYzFZClPygle7sMMWwjWtdHyOZuRoe9owd8F1gn+lmuweuV+H06w1aUiYWGIcEicgmgtp5yWJ3blTpRSFKN0ypaql0lRqPuXuPwbVsDC9h73JLI/knsmkE8iMESKv8ZsmHfNWtd0CkkvR7TOG5GqMcw9oI98p67QdjMumjLIG5EWlFLxJbvzgCcgoOK3DGFT3lAAvvOCdaCyYdzJ7i9BrcGYQUCDC0VZLqd9RmWl5QjXp+Sx9R9pGJf/B/ogfKcMuaRqxTLFJLM6R2J2WWgg0g84616huNrtNrjVelEsn3iu4Hspf0fn8iuO/sODvMj/zafoLIr9MSDN7UWED67gg+p3OWwDZLfaZYsOcgbh5oubmgQ2X2HTZWu8EX02ccv8CbZYVOd7CB85P74OkztgRQwlYhuzz7r+0eyd0akboklP9GM3GdRwUkhRDEFUo1mjoWME49HVA07pWIXf32844U3/Hlfg0M/uhhDk4lmHgYf7JExrdfunP6TOBGC1n1ju3J5IHrGthA6CR4yqWhp7s/De3UX0YOE4qOeL+pGQwnJQMA+o
  template:
    metadata:
      name: vibe-env
      namespace: vibe
    type: Opaque
